- name: print username and password
  hosts: localhost
  connection: local
  vars_prompt:     # using prompt
  - name: username
    prompt: Enter your username
    private: false

  - name: password
    prompt: Enter your password
    private: true

  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "username is: {{ username }} password is: {{ password }}"
