- name: variables from args
  hosts: localhost
  connection: local
  tasks:
  - name: print variables from args
    ansible.builtin.debug:
     msg: "Hi {{ Name }}, Good Morning"
      # - "hai, {{ Name | default('AK') }}, Good Morning!"