- name: install packages
  hosts: localhost
  conditions: local
  become: yes
  tasks: 
  - name: install package
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
    - mysql
    - nginx
    - zip